# Generated by Django 4.2 on 2026-07-17 13:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_customizable', models.BooleanField(default=False, help_text='Allow text customization')),
                ('customization_hint', models.CharField(blank=True, help_text='Placeholder for customization field', max_length=255, null=True)),
                ('has_models', models.BooleanField(default=False, help_text='Afficher les modèles pour ce produit')),
                ('model_type', models.CharField(choices=[('none', 'Aucun modèle'), ('numeric', 'Numérique (1-100)'), ('alpha', 'Alphabétique (A-Z)')], default='none', help_text='Type de modèle pour les produits personnalisables', max_length=10)),
                ('model_start', models.CharField(blank=True, help_text='Début de la plage (ex: 1 ou A)', max_length=3, null=True)),
                ('model_end', models.CharField(blank=True, help_text='Fin de la plage (ex: 100 ou Z)', max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video_url', models.URLField(blank=True, help_text='URL de la vidéo (YouTube, Vimeo)', max_length=500, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('numeric', 'Numérique'), ('alpha', 'Alphabétique')], max_length=10)),
                ('model_value', models.CharField(help_text='Valeur du modèle (ex: 1, 2, A, B, etc.)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.product')),
            ],
            options={
                'db_table': 'product_models',
                'ordering': ['display_order', 'model_value'],
                'unique_together': {('product', 'model_value')},
            },
        ),
    ]
